import type { Metadata } from "next";
import "./globals.css";
import { Container } from "@/components/Container";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: {
    default: "The blog - Este é um blog criado em NextJs",
    template: "%s | The blog",
  },
  description: "Generated by create next app",
};

// Esse Readonly é para não alterar o conteúdo
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body>
        <Container>
          <Header />

          <div>{children}</div>

          <footer>
            <h1 className="font-bold text-6xl text-center py-8">Footer</h1>
          </footer>
        </Container>
      </body>
    </html>
  );
}
