import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "The blog - Este é um blog criado em NextJs",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

// Esse Readonly é para não alterar o conteúdo

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="pt-BR">
      <body>
        <header>
          <h1>Header</h1>
        </header>

        <div className="bg-red-500">{children}</div>

        <footer>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
